*******************************************************************************
****** zxw_nand schematic zxw_lib  <vs>  zxw_nand layout zxw_lib
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(nmos) MOS                                        2       2
(pmos) MOS                                        2       2
                                             ------  ------
Total                                             4       4

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nmos) MOS                                        2       2           2       2
(pmos) MOS                                        2       2           2       2
                                             ------  ------      ------  ------
Total                                             4       4           4       4

Schematic and Layout Match
