*******************************************************************************
****** backupdiff schematic zxw_lib  <vs>  backupdiff layout zxw_lib
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(pmos) MOS                                       17      17
(nmos) MOS                                       17      17
                                             ------  ------
Total                                            34      34

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nmos) MOS                                       17      17          17      17
(pmos) MOS                                       17      17          17      17
                                             ------  ------      ------  ------
Total                                            34      34          34      34

Schematic and Layout Match
