*******************************************************************************
****** zxw_aoi2 schematic zxw_lib  <vs>  zxw_aoi2 layout zxw_lib
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(nmos) MOS                                        4       4
(pmos) MOS                                        4       4
                                             ------  ------
Total                                             8       8

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nmos) MOS                                        4       4           4       4
(pmos) MOS                                        4       4           4       4
                                             ------  ------      ------  ------
Total                                             8       8           8       8

Schematic and Layout Match
