0 0 dataAuditErrors
477 0 M1EOPC -- Min M1 Enclosure Of Pbus-Cnt < 1.00
479 0 M1EOPC -- Layer pbusCnt is not enclosed by pbusM1
481 0 M1EOPV -- Min M1 Enclosure Of Pbus Via < 1.0
483 0 M1EOPV -- Layer pbusVia is not enclosed by pbusM1
485 0 M2EOPV -- Min M2 Enclosure Of Pbus-Via < 1.00
487 0 M2EOPV -- Layer pbusVia is not enclosed by pbusM2
492 0 M2SCSP -- Mandatory M2 to SCribe-lane SPacing M2SCSP
494 0 PBAEOC -- Min PBus-Act Enclosure Of Cnt < 1.00
496 0 PBAEOC -- Layer pbusCnt is not enclosed by pbusAct
501 0 PBASCE -- Man PBus-Active to SCribe Edge PBASCE
502 0 PBSACW -- Min Per-BuS-ACtive Width < 14.00
503 0 PDSTPB -- PaD to STart of PerBus  < 10.00
504 0 PDSTPB -- Layer pbusAct not allowed to overlap PAD
505 0 PPL2SC -- PPLs to (defines) SCribe edge PPL2SC
510 0 SCRM1S -- Man SCRibe-lane to M1 Spacing SCRM1S
526 0 ACENND -- Man ACtive Enclosure of Nested-N-Drain == 0.50
533 0 NNDRNW -- Man Nested-N-DRaiN Width NNDRNW
544 0 NNDWEA -- Man Nested-N-Drain-Well Enclosure of Active == 0.50
549 0 NNDCHW -- Min Nested-N-Drain-CHannel Width  4.00
551 0 NNDEOC -- Min Nested-N-Drain Enclosure Of Contact < 0.20
553 0 NNDEOC -- Layer nvuNcnt is not enclosed by nstNsd
558 0 NNDGTS -- Man Nested-N-Drain to Gate Spacing NNDGTS
565 0 NNDWOG -- Man Nested-N-Drain-Well Overlap of Gate NNDWOG
570 0 NPBEAC -- Min NPBlk Enclosure of ACtive < 0.30
572 0 NPBEAC -- Layer nvuSd is not enclosed by nvuNpblkOrHole
578 0 NVCHL -- Min. NV-type nested-drain-CHannel-Length  5.00
580 0 NPBOGT -- Min NPBlk Overlap of GaTe < 1.50
582 0 NPBSRC -- Min NPBlk to SourRCe spacing  < 1.50
588 0 NUCHL -- Min NU-type nested-drain CHannel Length  3.00
608 0 ACENPD -- Man ACtive Enclosure of Nested-P-Drain == 0.70
613 0 NPDCHW -- Min Nested-P-Drain CHannel Width  2.30
615 0 NPDEOC -- Min Nested-P-Drain Enclosure Of Contact < 0.20
617 0 NPDEOC -- Layer pvuPcnt is not enclosed by nstPsd
622 0 NPDGTS -- Man Nested-P-Drain to GaTe Spacing NPDGTS
628 0 NPDRNW -- Man Nested-P-DRaiN Width NPDRNW
633 0 NPDWEA -- Min Nested-P-Drain-Well Enclosure of Active < 2.00
635 0 NPDWEA -- Layer pvuDrainDRC is not enclosed by pvuNwell
640 0 PPBEAC -- Min PPBlk Enclosure of ACtive < 0.30
642 0 PPBEAC -- Layer pvuPsd is not enclosed by pvuPpblkOrHole
648 0 PVCHL -- Min. PV-type nested-drain CHannel-Length  3.00
650 0 PPBOGT -- Min PPBlk Overlap of GaTe < 1.50
652 0 PPBSRC -- Min PPBlk to SouRCe spacing < 1.50
658 0 PUCHL -- Min PU-type nested-drain CHannel Length  3.00
686 0 NPBACS -- Min NPBlk to ACtive Spacing < 0.30
687 0 PPBACS -- Min PPBlk to ACtive Spacing < 0.30
691 0 T12TBS -- Tub-12v to TuB Spacing < 6.00
692 0 P12PDS -- Min P-act-12v to P-Diffusion Spacing < 2.00
694 0 T12END -- Tub-12v Enclosure of N-Diffusion < 0.50
696 0 T12END -- Layer v12Nsd is not enclosed by v12NNwell
698 0 T12EPD -- Tub-12v Enclosure of P-Diffusion < 2.00
700 0 T12EPD -- Layer v12Psd is not enclosed by v12PNwell
701 0 T12NDS -- Tub-12v to N-Diffusion Spacing < 2.00
702 0 T12PDS -- Tub-12v to P-Diffusion Spacing < 0.50
718 0 EXNCHW -- Min EXtended-N-drain CHannel Width  5.00
725 0 MWONXG -- Man Well Overlaps NX-type Gate MWONXG
733 0 MXPNDW -- Man eXtended-P/N-Drain active Width MXPNDW
742 0 NCEXDW -- Man N-Chan-field Enclosure of eXtended-Drain-Well == 0.50
744 0 NWEXND -- Min NWell Enclosure of eXtended-N-Drain  < 1.00
746 0 NWEXND -- Layer nzxDrainDRC is not enclosed by nzxNwell
755 0 NXDRFT -- Man NX-type extended-drain DRiFT  length NXDRFT
761 0 NZCHL -- Min NZ-type extended-drain CHannel Length  5.00
763 0 PXBXNG -- Min Poly eXtends Beyond eXtended-N-Gate < 1.00
765 0 PXBXNG -- Layer nzxDiffNotSd is not enclosed by nzxPoly1
771 0 NXCHL -- Min NX-type extended-drain CHannel Length  5.00
783 0 MWONTG -- Man Well Overlaps NT-type Gate MWONTG
791 0 MXPNDW -- Man eXtended-P/N-Drain active Width MXPNDW
800 0 NCEXDW -- Man N-Chan-field Enclosure of eXtended-Drain-Well == 0.50
806 0 NTCHL -- Min NT-type extended-drain CHannel Length  5.00
811 0 NTCHW -- Min NT-type extended-drain CHannel Width  5.00
818 0 NTDRFT -- Man NT-type ext-drain DRiFT  length for model accuracy only NTDRFT
820 0 NWEXND -- Min NWell Enclosure of eXtended-N-Drain  < 1.00
822 0 NWEXND -- Layer ntDrainDRC is not enclosed by ntNwell
823 0 PXBXNG -- Min Poly eXtends Beyond eXtended-N-Gate < 1.00
853 0 EXPCHW -- Min EXtended-P-drain CHannel Width  5.0
859 0 EXPGER -- Extended P gate requires pfield  
865 0 MXPNDW -- Man eXtended-P/N-Drain active Width MXPNDW
874 0 NCEXDW -- Man N-Chan-field Enclosure of eXtended-Drain-Well == 0.50
876 0 NWEOPF -- Min NWell Enclosure Of PField < 3.00
877 0 NWEOPF -- Min NWell Enclosure Of PField NWEOPF
879 0 PFEODA -- Min PField Enclosure of ext-Drain-Active < 1.00
880 0 PFEODA -- Min PField Enclosure of ext-Drain-Active PFEODA
881 0 PFNDSP -- Min P-Field to NDiff SPacing PFNDSP
882 0 PFNDSP -- Min P-Field to NDiff SPacing < 1.00
889 0 PFOLXP -- Man P-Field OverLap of eXtended-P-gate PFOLXP
890 0 PXBXNG -- Min Poly eXtends Beyond eXtended-N-Gate < 1.00
897 0 PXDRFT -- Man PX-type extended-drain DRiFT  length PXDRFT
903 0 EXPCHL -- EXPCHL_DESC  5.0
909 0 PZCHL -- Min PZ-type extended-drain CHannel Length  5.00
915 0 PXCHL -- Min PX-type extended-drain CHannel Length  5.00
921 0 PTCHL -- Min PT-type extended-drain CHannelLength  5.00
926 0 PTCHW -- Min PT-dev-type extended-drain CHannel Width  5.00
958 0 PFLDSP -- Min P-FieLD to P-FieLD SPacing < 4.00
961 0 PFPDSP -- Min P-Field to PDiffusion SPacing < 3.00
963 0 T20END -- Tub-20v Enclosure Of N-Diffusion < 1.00
965 0 T20END -- Layer v20Nsd is not enclosed by v20NNwell
967 0 T20EPD -- Tub-20v Enclosure Of P-Diffusion < 3.00
969 0 T20EPD -- Layer v20Psd is not enclosed by v20PNwell
970 0 T20NDS -- Tub-20v to N-Diffusion Spacing < 3.00
971 0 T20PDS -- Tub-20v to P-Diffusion Spacing < 1.00
977 0 T20TBS -- Tub-20v to TuB Spacing < 6.00
979 0 T20TBS -- Tub-20v to TuB Spacing < 6.00
983 0 MN40DRAREA -- N-device Drain Area mn40vDrain 26.01
990 0 MN40LC -- Poly enclosure of Deep N Well towards source MN40LC
997 0 MN40LD -- Deep N Well enclosure of drain active area MN40LD
1005 0 MN40LG1 -- Deep N Well space of channel active MN40LG1
1013 0 MN40LG2 -- N Well space of channel active MN40LG2
1020 0 MN40LP -- Poly space drain MN40LP
1029 0 MN40LS -- P Well Block enclosure of Deep N Well == 3.5
1038 0 MN40PBEONF -- P Well Block enclosure of N Channel Field == 1.0
1049 0 DNW40EONW -- 40 volt Deep N Well enclosure of N Well == 2.0
1053 0 MP40DRAREA -- P-device Drain Area mp40vDrain 26.01
1060 0 MP40LC -- P Well Block enclosure of source poly edge towards drain MP40LC
1065 0 MP40LD -- P Well Block space to drain active MP40LD
1073 0 MP40LG1 -- P Well Block Block enclosure of channel active towards drain MP40LG1
1084 0 MP40LG2 -- Pch Resurf overlap of channel active == 1.0
1089 0 MP40LP -- Poly space drain MP40LP
1098 0 MP40LS -- P Well Block overlap of nwell == 4.0
1109 0 MP40NWEOWT -- N Well overlap of source-well active WellTie == 2.0
1110 0 NA40VPGSP -- N+Active to Hard P+Guardbar of 40 Volt DeepNwell < 1.0
1119 0 NCFEO40DNW -- NchannelField overlap 40 Volt DeepNwell == 4.0
1121 0 NW40VPGSP -- Nwell to Hard P+Guardbar of 40 Volt DeepNwell < 2.0
1129 0 SKACSP -- Schottky ACtive SPacing SKACSP
1138 0 SKTEOA -- Schottky Tub Enclosure Of Active == 1.00
1141 0 shkHoleInPplsMissing -- The Ppls requires a hole in it above the anode diffusion to form the dschottky device.  
1142 0 shkPplsMissing -- Ppls above the anode diffusion is required to form the dschottky.  
1148 0 SKANW -- Schottky ANode Width SKANW
1154 0 SKCAW -- Schottky CAthode Width SKCAW
1159 0 SKCTPPS -- Schottky ConTact P+ Spacing SKCTPPS
1160 0 SKL -- Schottky contact Length  20.20
1164 0 NVOSKCT -- No nested vias over schottky contact NVOSKCT
1166 0 SKRP2 -- Schottky requires Poly 2 process SKRP2
1196 0 NCHNER -- NCHaN ERror if nchan is not identical to tub == 
1207 0 NCEXDW -- Man N-Chan-field Enclosure of eXtended-Drain-Well NCEXDW
1221 0 DIFRW -- WARNING - Resistors narrower than 0.8 u wide are not modeled accurately in simulation - WARNING < 0.8
1222 0 DIFW -- Min DIFfusion Width < 0.50
1223 0 WARNING - Resistor corners narrower than 0.8 u wide are not modeled accurately in simulation - WARNING
1234 0 DIFSP -- Min DIFfusion SPacing < 0.90
1236 0 TBEOPD -- TuB Enclosure Of P-Diffusion < 1.50
1238 0 TBEOPD -- Layer pDiff is not enclosed by nwNot40v
1242 0 TBNDSP -- TuB to N-Diffusion SPacing < 1.50
1247 0 TRANW -- Minimum TRANsistor Width  0.80
1248 0 TBEOND -- Active area overlap on nwell < 0.50
1249 0 TBPDSP -- TuB to P-Diffusion SPacing  0.00
1256 0 FLOTNW -- FLOaTing N-Wells  
1258 0 FLOTPW -- FLOaTing P-Wells  
1265 0 TUBRW -- WARNING - Resistors narrower than 5.00 u wide are not modeled accurately in simulation - WARNING < 5.00
1266 0 WARNING - Resistor corners narrower than 5.00 u wide are not modeled accurately in simulation - WARNING
1269 0 TUBW -- Min TUB Width < 2.50
1287 0 TUBSPR -- Min TUB Spacing related < 2.00
1289 0 TUBSP -- Min TUB SPacing < 4.00
1291 0 TUBSP -- Min TUB SPacing < 4.00
1292 0 TUBSP -- Min TUB SPacing < 4.00
1294 0 ACXBPY -- Min ACtive eXtension Beyond PolY < 0.65
1303 0 PYXBAC -- Min PolY eXtension Beyond ACtive < 0.50
1304 0 PYACSP -- Min PolY to ACtive SPacing < 0.20
1308 0 POLYW -- Min POLY Width < 0.60
1309 0 WARNING - Resistor corners narrower than 0.60 u wide are not modeled accurately in simulation - WARNING
1320 0 POLYSP -- Min POLY SPacing < 0.60
1322 0 NDEOGT -- Min N-Diffusion Enclosure Of GaTe < 0.65
1325 0 NPCOIN -- Nplus/Pplus COINcide  == 
1327 0 ZENER -- P/N Active not at the same potential < 0.90
1331 0 PDEOGT -- Min P-Diffusion Enclosure Of GaTe < 0.65
1332 0 PPACSP -- Min PPls to ACtive SPacing < 0.30
1334 0 PPEOAC -- Min PPls Enclosure Of ACtive < 0.30
1336 0 PPLSSP -- Min PPLS SPacing < 0.70
1337 0 PPLSW -- Min PPLS Width < 0.70
1339 0 ACEOCT -- Min ACtive Enclosure Of CnT < 0.30
1341 0 ACEOCT -- Layer CNT is not enclosed by ACT
1342 0 ACTPYS -- Min Active-ConTacts to any PolY Spacing < 0.40
1343 0 ACTPYS -- Layer actCnt not allowed to overlap allPoly
1345 0 APEOCT -- Min All-Poly Enclosure Of CnT < 0.20
1347 0 APEOCT -- Layer p1Cnt is not enclosed by POLY1
1349 0 AP2EOCT -- Min Poly2 Enclosure Of Cnt < 0.2
1351 0 AP2EOCT -- Layer p2Cnt is not enclosed by POLY2
1353 0 BUTCNA -- BUTted Cnts Not Allowed  
1355 0 CNTSP -- Min CNT SPacing < 0.50
1357 0 CNTW -- Man CNT Width  0.50
1358 0 CTOFLD -- CnT Over FieLD CTOFLD
1359 0 CTOVGT -- CnT OVer GaTe poly CTOVGT
1360 0 PCTACS -- Min Poly-ConTacts to ACtive Spacing < 0.40
1361 0 PCTACS -- Layer p1Cnt not allowed to overlap ACT
1362 0 CTNOM1 -- CnT with NO M1 cover CTNOM1
1364 0 M1EOCT -- Min M1 Enclosure Of CnT < 0.20
1366 0 M1EOCT -- Layer CNT is not enclosed by M1
1370 0 M1W -- Min M1 Width < 0.60
1371 0 WARNING - Resistor corners narrower than 0.60 u wide are not modeled accurately in simulation - WARNING
1382 0 M1SP -- Min M1 SPacing < 0.60
1386 0 WDM1SP -- Min WiDe M1 to M1 SPacing < 1.20
1388 0 M1EOVI -- Min M1 Enclosure Of VIa < 0.20
1390 0 M1EOVI -- Layer VIA is not enclosed by M1
1392 0 VIASP -- Min VIA SPacing < 0.60
1393 0 VIAW -- Man VIA Width  0.50
1394 0 VINOM1 -- VIa with NO M1 under VINOM1
1396 0 M2EOVI -- Min M2 Enclosure Of VIa < 0.20
1398 0 M2EOVI -- Layer VIA is not enclosed by M2
1399 0 VINOM2 -- VIa with NO M2 cover VINOM2
1403 0 M2W -- Min M2 Width < 0.70
1404 0 WARNING - Resistor corners narrower than 0.70 u wide are not modeled accurately in simulation - WARNING
1415 0 M2SP -- Min M2 SPacing < 0.70
1419 0 WDM2SP -- Min WiDe M2 to M2 SPacing < 1.20
1440 0 LNLYVIA1 -- Lonely VIA1 needs redundancy extra metal or patterning LNLYVIA1
1442 0 M2EOV2 -- Min M2 Enclosure Of Via2 < 0.20
1444 0 M2EOV2 -- Layer VI2 is not enclosed by M2
1445 0 V2NOM2 -- Via 2 with NO M2 under V2NOM2
1447 0 VI2SP -- Min VI2 SPacing < 0.80
1448 0 VI2W -- Man VI2 Width  0.50
1450 0 M3EOV2 -- Min M3 Enclosure Of Via2 < 0.20
1452 0 M3EOV2 -- Layer VI2 is not enclosed by M3
1453 0 V2NOM3 -- Via 2 with NO M3 covering V2NOM3
1457 0 M3W -- Min M3 Width < 0.80
1458 0 WARNING - Resistor corners narrower than 0.80 u wide are not modeled accurately in simulation - WARNING
1469 0 M3SP -- Min M3 SPacing < 0.70
1473 0 WDM3SP -- Min WiDe M3 to M3 Spacing < 1.20
1494 0 LNLYVIA2 -- Lonely VIA2 needs redundancy extra metal or patterning LNLYVIA2
1498 0 M1EOPD -- Min M1 Enclosure Of PaD < 3.00
1500 0 M1EOPD -- Layer padNotProbe is not enclosed by M1
1502 0 M2EOPD -- Min M2 Enclosure Of PaD < 2.40
1504 0 M2EOPD -- Layer padNotProbe is not enclosed by M2
1506 0 M3EOPD -- Min M3 Enclosure Of PaD < 1.20
1508 0 M3EOPD -- Layer padNotProbe is not enclosed by M3
1510 0 PADSP -- Min PAD SPacing < 12.00
1511 0 PADTAC -- PAD To ACtive spacing < 10.00
1512 0 PADTAC -- Layer padNotProbe not allowed to overlap ACT
1514 0 PADTM1 -- PAD To unrelated M1 < 8.00
1516 0 PADTM2 -- PAD To unrelated M2 < 8.00
1518 0 PADTM3 -- PAD To unrelated M3 < 8.00
1520 0 PADTPY -- PAD To unrelated Poly < 10.00
1521 0 PADTPY -- Layer padNotProbe not allowed to overlap poly1NoRes
1523 0 PADTPY2 -- PAD To unrelated Poly2 < 10.0
1524 0 PADTPY2 -- Layer padNotProbe not allowed to overlap poly2NoRes
1525 0 PADW -- Min PAD Width < 50.00
1526 0 PBPADW -- ProBepoint PAD Width < 5.00
1530 0 PDV1SP -- Pad/Via1 SPacing < 3.00
1531 0 PDV1V2 -- Pad/V1 to pad/V2 SPacing < 1.00
1532 0 PDV1V2 -- Layer padVia not allowed to overlap padVia2
1534 0 PDV2SP -- Pad/Via2 SPacing < 3.00
1536 0 MOPBPD -- Metal Overlap of ProBPD < 2.00
1538 0 MOPBPD -- Layer probePadM1 is not enclosed by probeM1
1540 0 MOPBPD -- Metal Overlap of ProBPD < 2.00
1542 0 MOPBPD -- Layer probePadM2 is not enclosed by probeM2
1544 0 MOPBPD -- Metal Overlap of ProBPD < 2.00
1546 0 MOPBPD -- Layer probePadM3 is not enclosed by probeM3
1547 0 PRBNOM -- PRoBpad with NO Metal PRBNOM
1548 0 PRBNOM -- PRoBpad with NO Metal PRBNOM
1549 0 PRBNOM -- PRoBpad with NO Metal PRBNOM
1551 0 BCEOTC -- Min BotCap plate Enclosure Of TopCap plate < 0.50
1553 0 BCEOTC -- Layer ppTopCap is not enclosed by ppBotCap
1554 0 P2ACSP -- Min Poly2 to ACtive SPacing < 0.20
1559 0 POLY2W -- Min POLY2 Width < 2.00
1560 0 WARNING - Resistor corners narrower than 2.00 u wide are not modeled accurately in simulation - WARNING
1571 0 PLY2SP -- Min POLY2 SPacing < 0.80
1573 0 TCACSP -- Min TopCap plate to ACtive SPace < 2.00
1574 0 TCACSP -- Layer ppTopCap not allowed to overlap actNotppTopCap
1575 0 TCCTSP -- Min TopCap plate to CnT SPacing  < 0.50
1576 0 TCPPSP -- Min TopCap to PPls SPace  < 2.00
1578 0 P2OP1EC -- Min Poly2 Over Poly1 Enclosure of Contact < 0.30
1580 0 HIREOP -- Min HIRes Enclosure Of Poly2 < 1.00
1581 0 HIRESW -- Min HIRES Width < 2.00
1583 0 HIRMSP -- Min HIRes Mask SPace < 1.00
1585 0 HIRP2S -- Min HIRes to Poly2 Space < 1.00
1586 0 HRPCSP -- Min HiR over Poly2 to Cnt SPace < 0.50
1587 0 HRPCSP -- Min HiR over Poly2 to Cnt SPace < 0.50
1590 0 THKGTS -- Min THKGT Spacing < 0.70
1591 0 THKGTW -- Min THKGT Width < 1.00
1594 0 TKACSP -- Min ThKgt to ACtive SPacing < 0.30
1596 0 TKEOAC -- Min ThKgt Enclosure Of ACtive < 0.30
1598 0 TKEOAC -- Layer thkgtAct is not enclosed by THKGT
1601 0 EMTRSZ -- Man Emitter diffusion Size ensures model performance  20.00
1602 0 EMTRSZ_S -- Man Emitter diffusion Size ensures model performance  4.1
1607 0 BJTCW -- Min Collector diffusion Width < 1.10
1612 0 BJTBSC -- Man Base diffusion to Collector diffusion ensures model performance BJTBSC
1618 0 BJTBW -- Man Base diffusion Width ensures model performance BJTBW
1623 0 BJTESB -- Man Emitter diffusion to Base diffusion ensures model performance BJTESB
1632 0 BJTTOE -- Man Tub Overlap to Emitter diffusion ensures model performance == 7.00
1640 0 BJTBSC_S -- Man Base diffusion to Collector diffusion ensures model performance BJTBSC_S
1646 0 BJTBW_S -- Man Base diffusion Width ensures model performance BJTBW_S
1651 0 BJTESB_S -- Man Emitter diffusion to Base diffusion ensures model performance BJTESB_S
1660 0 BJTTOE_S -- Man Tub Overlap to Emitter diffusion ensures model performance == 2.50
1688 0 EACEOC -- EC ACtive Enclosure of Contact < 2.00
1690 0 EACEOC -- Layer padCnt is not enclosed by EDIF
1691 0 EACEOT -- EC ACtive Overlap of Tub toward gate < 1.50
1695 0 EACX -- EC ACtive Spacing < 1.20
1696 0 ENCTGX -- EC N-device drain Contact To Gate Spacing < 6.20
1697 0 EPCTGX -- EC P-device drain Contact To Gate Spacing    < 4.60
1698 0 ESCTGX -- EC Source Contact To Gate Spacing < 1.35
1700 0 ETBEOC -- EC NTuB Enclosure of Contact < 1.00
1702 0 ETBEOC -- Layer padCnt is not enclosed by ENNWELL
1703 0 ETBGAX -- EC TuB to GAte Spacing < 1.50
1717 0 CNTRC -- Contacts should be in a double row and column < 0.50
1724 0 PY1ANT -- PolY1 ANTenna check (100:1 ratio)  100.00
1733 0 M1PANT -- Metal 1 to Poly gate ANTenna  1000.00
1744 0 M2PANT -- Metal 2 to Poly gate ANTenna  1000.00
1757 0 M3PANT -- Metal 3 to Poly gate ANTenna  1000.0
