*******************************************************************************
****** zxw_dffwrong schematic zxw_lib  <vs>  zxw_dffwrong layout zxw_lib
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(pmos) MOS                                       19      19
(nmos) MOS                                       19      19
                                             ------  ------
Total                                            38      38

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nmos) MOS                                       19      19          19      19
(pmos) MOS                                       19      19          19      19
                                             ------  ------      ------  ------
Total                                            38      38          38      38

Schematic and Layout Match
