*******************************************************************************
****** zxw_xor2 schematic zxw_lib  <vs>  zxw_xor2 layout zxw_lib
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(pmos) MOS                                        6       6
(nmos) MOS                                        6       6
                                             ------  ------
Total                                            12      12

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nmos) MOS                                        6       6           6       6
(pmos) MOS                                        6       6           6       6
                                             ------  ------      ------  ------
Total                                            12      12          12      12

Schematic and Layout Match
