*******************************************************************************
****** zxw_mux2to1 schematic zxw_lib  <vs>  zxw_mux2to1 layout2 zxw_lib
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(pmos) MOS                                        5       5
(nmos) MOS                                        5       5
                                             ------  ------
Total                                            10      10

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nmos) MOS                                        5       5           5       5
(pmos) MOS                                        5       5           5       5
                                             ------  ------      ------  ------
Total                                            10      10          10      10

Schematic and Layout Match
