*******************************************************************************
****** zxw_inv2 schematic zxw_lib  <vs>  zxw_inv2 layout zxw_lib
*******************************************************************************
                                                                                                                                                                                                                            
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(nmos) MOS                                        1       1
(pmos) MOS                                        1       1
                                             ------  ------
Total                                             2       2

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nmos) MOS                                        1       1           1       1
(pmos) MOS                                        1       1           1       1

Match Statistics
================                                  Total             Unmatched
Cell/Device                               schematic  layout   schematic  layout
(nmos) MOS                                        1       1           0       0
(pmos) MOS                                        1       1           0       0
                                             ------  ------      ------  ------
Total                                             2       2           0       0

Match Statistics for Nets                         4       4           0       0

=====================================================================[zxw_inv2]
====== Unbound Pin ============================================================
===============================================================================

S in1
S out1

=====================================================================[zxw_inv2]
====== Summary of Errors ======================================================
===============================================================================

Schematic  Layout     Error Type
---------  ------     ----------
 2          -         Unbound Pin

